image: node:22.9.0

stages:
  - format
  - lint
  - typecheck
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

format-job:
  stage: format
  script:
    - npm run format

lint-job:
  stage: lint
  script:
    - npm run lint

typecheck-job:
  stage: typecheck
  script:
    - npm run typecheck

build-job:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test-job:
  stage: test
  script:
    - npm test
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application... quand j'aurais un vps :)"
    - exit 1
  only:
    - main
