image: node:22.9.0

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - package-lock.json

stages:
  - install
  - format
  - lint
  - typecheck
  - build
  - test
  - deploy

install_dependencies:
  stage: install
  script:
    - echo "📦 Installing dependencies..."
    - npm ci --prefer-offline --no-audit --no-progress
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

format-job:
  stage: format
  script:
    - npm run format

lint-job:
  stage: lint
  script:
    - npm run lint

typecheck-job:
  stage: typecheck
  script:
    - npm run typecheck

build-job:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1h

test-job:
  stage: test
  script:
    - npm test

deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application... quand j'aurais un vps :)"
    - exit 1
  dependencies:
    - build-job
  only:
    - main
